In [1]:
from ukrdc_stats.utils import ukrdc_connection_from_env, cache_connection_from_env
from ukrdc_stats.calculators.chronic_kidney_disease import ChronicKidneyDiseaseBase
import datetime as dt 

facility = "RJZ"
ukrdc3 = ukrdc_connection_from_env()
ukrdc_stats_cache = cache_connection_from_env()

# run function to extract stats
#ukrdc_stats_cache.flushall()

ckd_calculator = ChronicKidneyDiseaseBase(ukrdc3, ukrdc_stats_cache, facility, dt.datetime(2023,1,1))

ckd_calculator.extract_stats()
ckd_calculator.recent_egfr_result()

patient cohort restored from cache

c:\Users\philip.main\Source\dashboard-stats\.venv\lib\site-packages\pandas\core\tools\datetimes.py:557: RuntimeWarning: invalid value encountered in cast
  arr, tz_parsed = tslib.array_with_unit_to_datetime(arg, unit, errors=errors)

In [2]:
ckd_calculator._patient_cohort.head()

,ukrdcid,birthtime,deathtime,admitreasoncode,serviceidcode,orderitemcode,enteredon,resultvalue,resultvalueunits
0,100029100,1959-07-30 01:00:00,NaT,NaN,QBLA1,NaN,2018-12-11 17:44:35,103,μmol/L
1,100029100,1959-07-30 01:00:00,NaT,NaN,QBLA1,NaN,2019-03-06 20:45:32,110,μmol/L
2,100029100,1959-07-30 01:00:00,NaT,NaN,QBLA1,NaN,2020-02-25 20:02:21,103,μmol/L
3,100029100,1959-07-30 01:00:00,NaT,NaN,QBLA1,NaN,2020-09-10 19:12:48,94,μmol/L
4,100064541,1947-11-11 00:00:00,NaT,NaN,QBLA1,NaN,2023-05-12 18:30:02,101,μmol/L

In [3]:
ckd_calculator._patient_cohort.head()

,ukrdcid,birthtime,deathtime,admitreasoncode,serviceidcode,orderitemcode,enteredon,resultvalue,resultvalueunits
0,100029100,1959-07-30 01:00:00,NaT,NaN,QBLA1,NaN,2018-12-11 17:44:35,103,μmol/L
1,100029100,1959-07-30 01:00:00,NaT,NaN,QBLA1,NaN,2019-03-06 20:45:32,110,μmol/L
2,100029100,1959-07-30 01:00:00,NaT,NaN,QBLA1,NaN,2020-02-25 20:02:21,103,μmol/L
3,100029100,1959-07-30 01:00:00,NaT,NaN,QBLA1,NaN,2020-09-10 19:12:48,94,μmol/L
4,100064541,1947-11-11 00:00:00,NaT,NaN,QBLA1,NaN,2023-05-12 18:30:02,101,μmol/L

In [4]:
ckd_calculator._patient_cohort['birthtime'].dtype

dtype('<M8[ns]')